### PR TITLE
Bug fixes

### LINKED ISSUE #197: [PE-D] Error msg formate
The first error msg looks a bit out of line...(sry for OCD-ing)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Isabella-L/ped#4

### PR DESCRIPTION
**Pull request by SvethaMahadevan**
Fixes #197 and #206

### CODE REVIEW

File: src/main/java/seedu/duke/parser/journal/ParserJournal.java [hunk 1]
```diff
@@ -81,195 +90,273 @@ public static boolean isValidNotebookCommand(String input) throws EmptyNoteArgum
...
+        try {
+            noteNameAndEntryName =
+                    noteNameAndEntryNameDetails.substring(noteNameAndEntryNameDetails.indexOf("n/")).trim();
+        } catch (Exception e) {
+            throw new InvalidAddEntryArgumentException();
+        }
+
+        try {
+            noteName = noteNameAndEntryName.substring(noteNameAndEntryName.indexOf("n/") + 2,
+                    noteNameAndEntryName.indexOf("e/")).trim();
```
Comment (swatimahadevan) [inline src/main/java/seedu/duke/parser/journal/ParserJournal.java:189]: The statement seem a bit lengthy. Consider extracting out index of e/ and n/ since you use these repeatedly.

File: src/main/java/seedu/duke/parser/journal/ParserJournal.java [hunk 2]
```diff
@@ -81,195 +90,273 @@ public static boolean isValidNotebookCommand(String input) throws EmptyNoteArgum
...
+        try {
+            noteNameAndEntryName =
+                    noteNameAndEntryNameDetails.substring(noteNameAndEntryNameDetails.indexOf("n/")).trim();
+        } catch (Exception e) {
+            throw new InvalidDeleteEntryArgumentException();
+        }
+
+        try {
+            noteName = noteNameAndEntryName.substring(noteNameAndEntryName.indexOf("n/") + 2,
+                    noteNameAndEntryName.indexOf("e/")).trim();
```
Comment (swatimahadevan) [inline src/main/java/seedu/duke/parser/journal/ParserJournal.java:323]: These statements also are quite lengthy.

File: src/main/java/seedu/duke/parser/journal/ParserJournal.java (hunk 1 above)
Comment (SvethaMahadevan) [reply src/main/java/seedu/duke/parser/journal/ParserJournal.java:189]: Yes. Will rectify in next PR.
