### PR TITLE
Full implementation of Food commands

### LINKED ISSUE #38: Exception handling on main
Prints error message to user on wrong command

### PR DESCRIPTION
**Pull request by ngnigel99**
Add exception handling, print error messages on Duke
Reorganize Food implementation
Add folder creation capability,  write to text
Fix #38

### CODE REVIEW

File: src/main/java/seedu/duke/Duke.java [hunk 1]
```diff
@@ -30,21 +30,18 @@
...
 
-    /**
-     * Reads and executes command from user inputs.
-     */
     private static void run() {
         ui.printGreeting();
         Scanner in = new Scanner(System.in);
         while (true) {
-            String userInput = ui.getUserInput(in);
+            String userInput = in.hasNextLine() ? in.nextLine()  : null;
```
Comment (ngnigel99) [inline src/main/java/seedu/duke/Duke.java:37]: I changed this from ui to just a scanner

File: src/main/java/seedu/duke/storage/StorageTasks.java [hunk 2]
```diff
@@ -12,6 +12,10 @@
 
 //@author swatim
 public class StorageTasks {
+    //author ngnigel99 - create in folder
+    public static final String folderName = "tasksdata/";
+    public static final String fileName   = "scheduleTasks.txt";
+    public static final String filePath = folderName + fileName;
```
Comment (ngnigel99) [inline src/main/java/seedu/duke/storage/StorageTasks.java:18]: @swatimahadevan I added these variables instead of using a constant, so your data would be organised into `tasksdata/` folder. feel free to change the name

File: text-ui-test/EXPECTED.TXT [hunk 3]
```diff
@@ -1,3 +1,11 @@
+Hey, I didn't find directory fooddata/
+adding fooddata/ into repository...
+Hey, I didn't find list.txt in fooddata/!
+creating new file...
+Hey, I didn't find directory tasksdata/
+adding tasksdata/ into repository...
+Hey, I didn't find scheduleTasks.txt in tasksdata/!
+creating new file...
```
Comment (ngnigel99) [inline text-ui-test/EXPECTED.TXT:8]: @swatimahadevan the food data folder would be instantiated too, as i modified the `load` functionality

File: src/main/java/seedu/duke/storage/Storage.java [hunk 4]
```diff
@@ -60,17 +62,27 @@ public void writeDataOntoSaveFile(String filePath, ArrayList<String> data) throw
...
+            tasks = StorageTasks.dataToTask(data);
+            TaskList tasksList = new TaskList();
+            for (int i = 0; i < tasks.size(); i++) {
+                tasksList.addTask(tasks.get(i));
+            }
+            return tasksList;
+        } catch (FileNotFoundException e) {     //author ngnigel99 - create new file
+            File f = new File(StorageTasks.filePath);
+            System.out.println("Hey, I didn't find " + StorageTasks.fileName + " in " + StorageTasks.folderName + "!");
+            System.out.println("creating new file...");
```
Comment (ngnigel99) [inline src/main/java/seedu/duke/storage/Storage.java:85]: @swatimahadevan here, I checked `FileNotFoundException` on creating a new file for new users, and used a variable in `Storage` rather than `Messages`. Was wondering if you could shift some of your specific operations into `StorageTasks` instead.

File: src/main/java/seedu/duke/storage/Storage.java [hunk 5]
```diff
@@ -60,17 +62,27 @@ public void writeDataOntoSaveFile(String filePath, ArrayList<String> data) throw
     public void writeTaskList(TaskList taskList) throws IOException {
         ArrayList<Task> tasks = taskList.getTaskList();
         ArrayList<String> data = StorageTasks.tasksToData(tasks);
-        writeDataOntoSaveFile(STORAGE_FILEPATH_SCHEDULE, data);
+        writeDataOntoSaveFile(StorageTasks.filePath, data); //author ngnigel99
```
Comment (ngnigel99) [inline src/main/java/seedu/duke/storage/Storage.java:65]: @swatimahadevan  modified this bit

File: src/main/java/seedu/duke/storage/Storage.java (hunk 4 above)
Comment (ngnigel99) [reply src/main/java/seedu/duke/storage/Storage.java:85]: for example, write and read task list because they are specific to a task list

File: src/main/java/seedu/duke/storage/StorageTasks.java (hunk 2 above)
Comment (ngnigel99) [reply src/main/java/seedu/duke/storage/StorageTasks.java:18]: #41
